name: CI
on: [push, pull_request]
jobs:
  python-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Python setup
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: tox install
        run: pip install tox

      - name: Python 3.8, Django 3.2 Unit Tests
        run: tox -e py38-django32

      - name: Upload coverage to CodeCov
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.xml
          fail_ci_if_error: true
