name: CI
on: [push, pull_request]
jobs:
  python-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Python setup
        uses: actions/setup-python@v2
        with:
          python-version: "2.7" # Change Python version to 2.7

      - name: Install dependencies
        run: |
          pip install tox
          pip install "Django==1.11.21"

      - name: Run tests
        run: tox -e py27-django111 # Adjust tox environment for Python 2.7 and Django 1.11

      - name: Upload coverage to CodeCov
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.xml
          fail_ci_if_error: true
